import type { AgentProfile, AgentTask, AgentTaskResult } from "./agentTypes";
import { DEEPSEEK_MODEL, getDeepSeekClient } from "./deepseekClient";

export type ProfessionalAgentConfig = {
  role: string;
  objective: string;
  reportTitle: string;
  sections: string[];
  artifactNames: string[];
  fallbackSummary: string;
};

type ProfessionalAgentOutput = {
  summary: string;
  output: string;
  artifacts: string[];
  scoreSuggestion: number;
};

export async function runProfessionalAgent(
  agent: AgentProfile,
  task: AgentTask,
  config: ProfessionalAgentConfig,
): Promise<AgentTaskResult> {
  try {
    const client = getDeepSeekClient();
    const completion = await client.chat.completions.create({
      model: DEEPSEEK_MODEL,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: buildSystemPrompt(config) },
        { role: "user", content: buildUserPrompt(agent, task, config) },
      ],
    });
    const content = completion.choices[0]?.message?.content;

    if (!content) {
      throw new Error("DeepSeek returned empty content");
    }

    const parsed = parseOutput(content);
    console.log(`[AgentVerse] DeepSeek ${agent.category} agent completed`);

    return {
      taskId: task.id,
      agentId: agent.id,
      summary: parsed.summary,
      output: parsed.output,
      artifacts: parsed.artifacts,
      scoreSuggestion: parsed.scoreSuggestion,
      status: "success",
      executionMode: "deepseek",
      completedAt: new Date().toISOString(),
    };
  } catch {
    console.warn(`[AgentVerse] DeepSeek unavailable, using ${agent.category} fallback`);
    return buildFallbackResult(agent, task, config);
  }
}

function buildSystemPrompt(config: ProfessionalAgentConfig): string {
  return [
    "AgentVerse = Agent LinkedIn + Agent GitHub + Agent Reputation Protocol.",
    `You are not a generic chatbot. You are a professional ${config.role}.`,
    config.objective,
    "Your output becomes a professional Agent Portfolio artifact and affects Reputation Score.",
    "Return JSON only without Markdown code fences.",
    'Return this shape: {"summary":"one sentence professional achievement","output":"complete Markdown professional artifact","artifacts":["artifact name"],"scoreSuggestion":1}',
    "scoreSuggestion must be a number from 1 to 5.",
    `The Markdown output title must be: # ${config.reportTitle}`,
    `Include these sections: ${config.sections.map((section) => `## ${section}`).join(", ")}.`,
  ].join("\n");
}

function buildUserPrompt(
  agent: AgentProfile,
  task: AgentTask,
  config: ProfessionalAgentConfig,
): string {
  return [
    `Agent: ${agent.name}`,
    `Agent ID: ${agent.id}`,
    `Category: ${agent.category}`,
    `Description: ${agent.description}`,
    `Skills: ${agent.skills.join(", ")}`,
    `Task ID: ${task.id}`,
    `Task title: ${task.title}`,
    `Task description: ${task.description}`,
    `Task input: ${task.input}`,
    `Expected artifact types: ${config.artifactNames.join(", ")}`,
    "Return JSON exactly matching the requested schema.",
  ].join("\n");
}

function parseOutput(content: string): ProfessionalAgentOutput {
  const parsed: unknown = JSON.parse(content);

  if (!isProfessionalAgentOutput(parsed)) {
    throw new Error("DeepSeek returned invalid professional agent JSON");
  }

  return {
    ...parsed,
    scoreSuggestion: clampScore(parsed.scoreSuggestion),
  };
}

function isProfessionalAgentOutput(value: unknown): value is ProfessionalAgentOutput {
  if (!value || typeof value !== "object") {
    return false;
  }

  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.summary === "string" &&
    typeof candidate.output === "string" &&
    Array.isArray(candidate.artifacts) &&
    candidate.artifacts.every((artifact) => typeof artifact === "string") &&
    typeof candidate.scoreSuggestion === "number"
  );
}

function buildFallbackResult(
  agent: AgentProfile,
  task: AgentTask,
  config: ProfessionalAgentConfig,
): AgentTaskResult {
  const sections = config.sections.flatMap((section) => [
    `## ${section}`,
    fallbackSectionText(section, agent, task, config),
    "",
  ]);

  return {
    taskId: task.id,
    agentId: agent.id,
    summary: config.fallbackSummary,
    output: [
      `# ${config.reportTitle}`,
      "",
      `> Fallback demo generated by ${agent.name} because DeepSeek was unavailable.`,
      "",
      ...sections,
    ].join("\n"),
    artifacts: config.artifactNames.map((artifact) => `${task.input} ${artifact}`),
    scoreSuggestion: 3,
    status: "success",
    executionMode: "fallback",
    completedAt: new Date().toISOString(),
  };
}

function fallbackSectionText(
  section: string,
  agent: AgentProfile,
  task: AgentTask,
  config: ProfessionalAgentConfig,
): string {
  if (section.toLowerCase().includes("portfolio")) {
    return `This ${config.role} result records a completed professional task and reusable evidence for the AgentVerse portfolio.`;
  }

  return `${agent.name} prepared a demo-safe ${section.toLowerCase()} for "${task.title}" using the supplied input: ${task.input}.`;
}

function clampScore(score: number): number {
  return Math.min(5, Math.max(1, score));
}
