const fs = require("fs");
const path = require("path");

const AgentRegistry = require("../artifacts/contracts/AgentRegistry.sol/AgentRegistry.json");
const ReputationProtocol = require("../artifacts/contracts/ReputationProtocol.sol/ReputationProtocol.json");

const outDir = path.join(__dirname, "..", "abis");
fs.mkdirSync(outDir, { recursive: true });

fs.writeFileSync(
  path.join(outDir, "AgentRegistry.json"),
  JSON.stringify(AgentRegistry.abi, null, 2)
);

fs.writeFileSync(
  path.join(outDir, "ReputationProtocol.json"),
  JSON.stringify(ReputationProtocol.abi, null, 2)
);

const ts = [
  "// Auto-generated by Hardhat compile. Do not edit manually.",
  "// Regenerate: npx hardhat compile && node scripts/extract-abis.js",
  "",
  "export const AGENT_REGISTRY_ABI = " + JSON.stringify(AgentRegistry.abi, null, 2) + " as const;",
  "",
  "export const REPUTATION_PROTOCOL_ABI = " + JSON.stringify(ReputationProtocol.abi, null, 2) + " as const;",
  "",
  "// Fill these from your .env / deployment output:",
  "//   VITE_AGENT_REGISTRY_ADDRESS=",
  "//   VITE_REPUTATION_PROTOCOL_ADDRESS=",
  "export const CONTRACTS = {",
  "  AGENT_REGISTRY: import.meta.env.VITE_AGENT_REGISTRY_ADDRESS ?? '',",
  "  REPUTATION_PROTOCOL: import.meta.env.VITE_REPUTATION_PROTOCOL_ADDRESS ?? '',",
  "} as const;",
].join("\n");

fs.writeFileSync(path.join(outDir, "contracts.ts"), ts);

console.log("ABIs exported to abis/");
console.log("  abis/AgentRegistry.json");
console.log("  abis/ReputationProtocol.json");
console.log("  abis/contracts.ts");
